### ISSUE TITLE
Deserialize of Contant entity cause Exception if Telegram user has no last name

### ISSUE THREAD

**Issue by dkirillov-radio** [luzrain/TelegramBotApi#5]
Now:
` 
/**
  * Optional. Contact's last name
  */
public string $lastName,
`

Must be:
`
/**
  * Optional. Contact's last name
  */
public string|null $lastName = null,
`

https://github.com/luzrain/telegram-bot-api/blob/a4db74bb92f990808bc117ac7fcf0b0aff8f4d37/src/Type/Contact.php#L28

**Comment by luzrain** [comment]
Thank you for reporting this bug. It has been fixed in the [latest release](https://github.com/luzrain/telegram-bot-api/releases)
